const LinkConstants = {
    GET_ALL_REQUEST: 'LINKS_GET_ALL_REQUEST',
    GET_ALL_SUCCESS: 'LINKS_GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'LINK_GET_ALL_FAILURE',
    GET_REQUEST: 'LINKS_GET_REQUEST',
    GET_SUCCESS: 'LINKS_GET_SUCCESS',
    GET_FAILURE: 'LINK_GET_FAILURE',
    SAVE_REQUEST: 'LINKS_SAVE_REQUEST',
    SAVE_SUCCESS: 'LINKS_SAVE_SUCCESS',
    SAVE_FAILURE: 'LINK_SAVE_FAILURE',
    DELETE_REQUEST: 'LINKS_DELETE_REQUEST',
    DELETE_SUCCESS: 'LINKS_DELETE_SUCCESS',
    DELETE_FAILURE: 'LINK_DELETE_FAILURE',
    LIKE_REQUEST: 'LINKS_LIKE_REQUEST',
    LIKE_SUCCESS: 'LINKS_LIKE_SUCCESS',
    LIKE_FAILURE: 'LINK_LIKE_FAILURE',
    UNLIKE_REQUEST: 'LINKS_UNLIKE_REQUEST',
    UNLIKE_SUCCESS: 'LINKS_UNLIKE_SUCCESS',
    UNLIKE_FAILURE: 'LINK_UNLIKE_FAILURE',
};

export default LinkConstants;
